import type { Metadata } from 'next';
import '../styles/globals.css';
// fonts
import { geist } from '@/styles/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={geist.className} suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}
